version: "1.0"
services:
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/client
      - /usr/client/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend-app

  backend-app:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/server
      - /usr/server/node_modules
    environment:
      - NODE_ENV=development
